[project]
name = ""
version = ""
description = ""
authors = [
]
dependencies = [
    "aocd>=0.1",
    "numpy>=1.26.3",
    "ipdb>=0.13.13",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

